export enum Command {
  Palette = 'palette',
  NewTab = 'newTab',
  SplitSideBySide = 'splitSideBySide',
  SplitTopBottom = 'splitTopBottom',
  NewWorkspace = 'newWorkspace',
  Projects = 'projects',
  Settings = 'settings',
  ClosePane = 'closePane',
  FocusPaneLeft = 'focusPaneLeft',
  FocusPaneRight = 'focusPaneRight',
  FocusPaneUp = 'focusPaneUp',
  FocusPaneDown = 'focusPaneDown',
  PreviousCommand = 'previousCommand',
  NextCommand = 'nextCommand',
  SwapPaneLeft = 'swapPaneLeft',
  SwapPaneRight = 'swapPaneRight',
  SwapPaneUp = 'swapPaneUp',
  SwapPaneDown = 'swapPaneDown',
  MoveTabLeft = 'moveTabLeft',
  MoveTabRight = 'moveTabRight',
  NextTab = 'nextTab',
  PreviousTab = 'previousTab',
  RestoreTab = 'restoreTab',
  ToggleExplorer = 'toggleExplorer',
  ToggleGit = 'toggleGit',
  ToggleNotes = 'toggleNotes',
  ToggleStatusLog = 'toggleStatusLog',
  ToggleSidebar = 'toggleSidebar',
  TogglePaneZoom = 'togglePaneZoom',
  EqualizePanes = 'equalizePanes',
  MovePaneToNewTab = 'movePaneToNewTab',
  JoinWaitingAgent = 'joinWaitingAgent',
  CreateWorktree = 'createWorktree',
  OpenBrowser = 'openBrowser',
}

export const LEADER_KEYS: Record<string, Command> = {
  p: Command.Palette,
  t: Command.NewTab,
  v: Command.SplitSideBySide,
  h: Command.SplitTopBottom,
  w: Command.NewWorkspace,
  f: Command.Projects,
  n: Command.CreateWorktree,
  e: Command.ToggleExplorer,
  g: Command.ToggleGit,
  o: Command.ToggleNotes,
  l: Command.ToggleStatusLog,
  b: Command.ToggleSidebar,
  ',': Command.Settings,
  x: Command.ClosePane,
  m: Command.TogglePaneZoom,
  '=': Command.EqualizePanes,
  '!': Command.MovePaneToNewTab,
  z: Command.RestoreTab,
  a: Command.JoinWaitingAgent,
  u: Command.OpenBrowser,
  ArrowRight: Command.FocusPaneRight,
  ArrowDown: Command.FocusPaneDown,
  ArrowLeft: Command.FocusPaneLeft,
  ArrowUp: Command.FocusPaneUp,
  PageUp: Command.MoveTabLeft,
  PageDown: Command.MoveTabRight,
}

export const LEADER_SHIFT_ARROW_KEYS: Record<string, Command> = {
  ArrowRight: Command.SwapPaneRight,
  ArrowDown: Command.SwapPaneDown,
  ArrowLeft: Command.SwapPaneLeft,
  ArrowUp: Command.SwapPaneUp,
}

export const DIRECT_PAGE_KEYS: Record<string, Command> = {
  PageUp: Command.MoveTabLeft,
  PageDown: Command.MoveTabRight,
}

export const DIRECT_LETTER_KEYS: Record<string, Command> = {
  p: Command.Palette,
  t: Command.NewTab,
  d: Command.SplitSideBySide,
  h: Command.SplitTopBottom,
  w: Command.NewWorkspace,
  x: Command.ClosePane,
  m: Command.TogglePaneZoom,
  z: Command.RestoreTab,
  e: Command.ToggleExplorer,
  g: Command.ToggleGit,
  o: Command.ToggleNotes,
  l: Command.ToggleStatusLog,
  b: Command.ToggleSidebar,
  a: Command.JoinWaitingAgent,
}

export const DIRECT_ARROW_KEYS: Record<string, Command> = {
  ArrowRight: Command.FocusPaneRight,
  ArrowDown: Command.FocusPaneDown,
  ArrowLeft: Command.FocusPaneLeft,
  ArrowUp: Command.FocusPaneUp,
  PageUp: Command.PreviousCommand,
  PageDown: Command.NextCommand,
}
